# Generated by Django 3.0.5 on 2020-05-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeitem',
            old_name='ingredients',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='time_required',
            field=models.CharField(default='', max_length=30),
        ),
    ]
